### ISSUE TITLE
arrow buttons should PAGE up (go from 1-16 to 17-32)

### ISSUE THREAD

**Issue by bendichter** [bendichter/ecogVIS#3]

**Comment by luiztauffer** [comment]
The double arrow are doing this: ^^ or vv
Do you wanna change this? I thought that an intermediate navigation could also be interesting

**Comment by bendichter** [comment]
oh sorry, I meant arrow keys. The key nav should map to ^^ and vv

**Comment by luiztauffer** [comment]
The keys 'page up' and 'page down' were mapping to page moves on channels dimension already.
I changed it anyway to what you said.
